id: P006868
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD53745
  title: མི་ཉག་མཆོད་རྟེན་གྱི་དཀར་ཆག་དད་གསུམ་ཉིན་བྱེད་འདྲེན་པའི་སྐྱ་རེངས
  author: ''
  volumes:
    7fcb0acbdb84412abbe35716104bae58:
      image_group_id: I1PD53760
      title: ''
      volume_number: 1
      total_pages: 46
      base_file: v001.txt
