id: IC0BAA357
legacy_id: P006868
ocr_import_info:
  bdrc_scan_id: W1PD53745
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T05:49:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:45:46.284426+00:00'
last_modified: 2022-09-01 12:45:50.356991
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD53745
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD53745
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཉག་མཆོད་རྟེན་གྱི་དཀར་ཆག་དད་གསུམ་ཉིན་བྱེད་འདྲེན་པའི་སྐྱ་རེངས།
  author: བཤད་སྒྲུབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9575471774961963
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1PD53760:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD53760
      total_pages: 46
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD53760.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9575471774961963
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
